---

# Update repositories

- hosts: all
  become: true
  pre_tasks:

  - name: update repository index apt
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: update repository index opensuse
    zypper:
      name: openssl
      update_cache: yes
    when: ansible_distribution == "openSUSE Tumbleweed"

# Update software

  - name: Update all packages on OpenSUSE
    zypper:
      name: '*'
      state: latest
    when: ansible_distribution == "openSUSE Tumbleweed"

  - name: Update all packages on Ubuntu/Debian
    apt:
      name: '*'
      state: latest
    when: ansible_distribution == "Debian"

# Install apache & php - Ubuntu server

- hosts: web
  become: true
  tasks:

  - name: Install apache web server
    apt:
      pkg:
      - apache2
      - php
      - libapache2-mod-php
      state: latest
# NFS

- hosts: dns
  become: true
  tasks:

  - name: Store dns file into /extra directory from server
    ansible.builtin.fetch:
      src: /etc/named.conf
      dest: /home/usuario/Proyectos/_ansible/files_project01/extra/

# Install dns server - Opensuse Tumbleweed
- hosts: dns
  become: true
  tasks:

  - name: Install Dns server - Opensuse
    zypper:
      name: dhcp_dns_server
      type: pattern
      state: latest
