---

# Update repositories 
- hosts: all
  become: true
  pre_tasks:

  - name: update repository index apt
    apt:
      update_cache: yes
    when: ansible_distribution == ["Ubuntu", "Debian"]

# Install web service (apache http server) and php compatibility
- hosts: web
  become: true
  tasks:

  - name: install apache2 package to ubuntu vm
    apt:
      name: apache2
      state: latest

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest


##############################
############ NFS #############

#Server

# Copy existent file (/etc/exports)
# Inventory to use a single target for this task (Web - Ubuntu server 20.04 LTS)
# Keeps a backup into the server itself

  - name: add exports file to server
    ansible.builtin.copy:
      src: /home/usuario/Proyectos/_ansible/files_base/extra/exports
      dest: /etc/exports
      owner: root
      group: root
      mode: '0644'
      backup: yes

# Client

# Take fstab file - backup
# Inventory to use single target for this task (Work - Debian 10)

- hosts: work
  become: true
  tasks:

  - name: Store file into /extra directory from client
    ansible.builtin.fetch:
      src: /etc/fstab
      dest: /home/usuario/Proyectos/_ansible/files_base/extra/



##############################
##############################


# Add software to Debian - IDE for communication with Ubuntu Server

  - name: Install atom on Debian Workstation
    apt:
      deb: https://atom.io/download/deb



#To-do list

# mysql-server
# mod-php-mysql? -specific user for client?
#


