---
# Update repositories into diferent linux distributions
- hosts: all
  become: true
  pre_tasks:

  - name: update repository index apt
    apt:
      update_cache: yes
    when: ansible_distribution == ["Ubuntu", "Debian"]

  - name: install atom on debian client from official site
    apt:
      deb: https://atom.io/download/deb
    when: ansible_distribution == 'Debian'

  - name: update repository index dnf
    yum:
      update_cache: yes
    when: ansible_distribution == 'RedHat'

  - name: update repository index opensuse
    zypper:
      name: openssl
      state: present
      update_cache: yes
    when: ansible_distribution == 'Suse'

  - name: update opensuse vm
    zypper:
      name: '*'
      state: latest
    when: ansible_distribution == 'Suse'

# Install web service (apache http server) and php compatibility
- hosts: web
  become: true
  tasks:

  - name: install apache2 package to ubuntu vm
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == 'Ubuntu'

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == 'Ubuntu'

# Add repo to fedora (software resource)
  - name: Add epel repository to fedora vm
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    when: ansible_distribution == 'RedHat'

# Add software to opensuse
- hosts: dev
  become: true
  tasks:

  - name: Add neofetch to opensuse vm
    zypper:
      name: neofetch
      state: latest  

# Add software to Debian - IDE for communication with Ubuntu Server
- hosts: work
  become: true
  tasks:

  - name: Install atom on Debian Workstation
    apt:
      deb: https://atom.io/download/deb
